---
# tasks file for aldserver/
- name: Install packages 
  apt: name={{ item }} state=latest
  loop:
    - "ald-server-common"
    - "ald-server-parsec"
    - "ald-server-dc"
    - "smolensk-security-ald"

- name: create hosts file
  copy:
    dest: /etc/hosts
    content: |
            127.0.0.1      localhost
            {{ ansible_host }}     {{ ansible_hostname }}.{{ REALM.lower() }} {{ ansible_hostname }}     
  
  # if NetworkManager is enabled
- name: Add IPv4 DNS server address
  shell: nmcli con mod {{ conname }} ipv4.dns {{ dnsip }} && nmcli con mod {{ conname }} ipv4.dns-search {{ REALM.lower() }}
  notify: Restart NM
  when: NetworkManager == true

  # if NetworkManager is disabled
- name: generate resolv conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
  when: NetworkManager == false 
        
- name: setting up ntp
  copy: 
    src: ntp.conf 
    dest: /etc/ntp.conf
  notify: Restart ntp
  
- name: enable ntp
  service: name=ntp state=started enabled=yes

- name: create ald config file
  template:
    src: ald.conf.j2
    dest: /etc/ald/ald.conf
    
- name: Create passfile
  copy:
    dest: /tmp/passfile
    content: |
            K/M:{{ aldpass }}
            admin/admin:{{ aldpass }}
    mode: 0600
    owner: root

- name: init ald
  shell: ald-init init -f --pass-file /tmp/passfile && rm /tmp/passfile
