---
# tasks file for aldserver/
  - name: Install packages 
    apt: name={{ item }} state=latest
    loop:
      - "ald-server-common"
      - "ald-server-parsec"
      - "ald-server-dc"
      - "smolensk-security-ald"
     
  - name: create hosts file
    template:
      src: hosts.j2
      dest: /etc/hosts
  
    # if NetworkManager is enabled
  - name: Add IPv4 DNS server address
    shell: nmcli con mod {{ conname }} ipv4.dns {{ dnsip }} && nmcli con mod {{ conname }} ipv4.dns-search {{ REALM.lower() }}
    notify: Restart NM
    when: NetworkManager == true

    # if NetworkManager is disabled
  - name: generate resolv conf
    template:
      src: resolv.conf.j2
      dest: /etc/resolv.conf
    when: NetworkManager == false 
        
  - name: setting up ntp
    template: 
      src: ntp.conf.j2 
      dest: /etc/ntp.conf
    notify: Restart ntp
    
  - name: enable ntp
    service: name=ntp state=started enabled=yes
  
  - name: create ald config file
    template:
      src: template/ald.conf.j2
      dest: /etc/ald/ald.conf
    
  - name: Create passfile
    template:
      src: template/passfile.j2 
      dest: /home/admuser/passfile
      mode: 0600
      owner: root
      group: root

  - name: init ald
    shell: ald-init init -f --pass-file /home/admuser/passfile && rm /home/admuser/passfile
